### ISSUE TITLE
Document non-enumerable properties

### ISSUE THREAD

**Issue by robintindale** [sketch-hq/SketchAPI#327]
![image](https://user-images.githubusercontent.com/2700528/50730264-1d156a80-1141-11e9-9f25-786df4d96b0f.png)

will this line actually work? as far as I can tell, a layer has no valid method for `sharedStyle`, and you just have to get the `sharedStyleId` and then look it up yourself?

**Comment by mathieudutour** [comment]
a styled layer does have a `sharedStyle` property, it's just not enumerable: https://github.com/BohemianCoding/SketchAPI/blob/develop/Source/dom/layers/StyledLayer.js#L61. It also won't show when doing `layer.toJSON()`.

For now, the documentation only shows the enumerable properties and I really should start to document the other. The reason it's not enumerable to avoid circular references (for example if `layer.parent` is enumerable, `console.log(layer)` would be an infinite loop (probably because of my terrible algorithm but that's another story)).

So I'll rename this issue to "Document non-enumerable properties" 😄

**Comment by robintindale** [comment]
Ah yeah - I was testing it on a text layer for some reason :p but I guess that should have the same property for consistency?

**Comment by mathieudutour** [comment]
hum it should since `Text` is a subclass of `StyledLayer`. Maybe there is a bug there?

**Comment by robintindale** [comment]
repro seems to be if the style is a remote shared style

**Comment by robintindale** [comment]
oh yeah - it's the same for layer styles too, if the style is remote, `sharedStyle` is `null`

**Comment by mathieudutour** [comment]
Ah interesting. I'll have a look tomorrow

**Comment by robintindale** [comment]
moved to #328

**Comment by mathieudutour** [comment]
I don't think that's actually fixed. There are a bunch of non-enumerable properties, not just `sharedStyle` ([like `parent`, `master`, etc.](https://github.com/sketch-hq/SketchAPI/search?q=enumerable%3A+false%2C&unscoped_q=enumerable%3A+false%2C)). 
The reason why they weren't listed next to the other properties is because they are conceptually very different. They are more like helpers that can be constructed from the rest of the API, and they aren't showing up when logging an object (cause they would create circular references most of the time).

**Comment by christianklotz** [comment]
Ok cool, re-opening in this case. Just to confirm, the circular references would be created during logging, right?

Public properties, i.e. everything that doesn't have a `_` or `__` prefix should still be documented since they were created for a reason. The fact they can't be enumerated is an implementation detail, albeit quite a substantial one. As an API consumer I do want to know about this properties though as the number of questions on the forum or in issues have shown.

**Comment by mathieudutour** [comment]
Totally, I'm just saying they should maybe be documented in a separate "sub-section" because they are conceptually different from "normal" properties.

**Comment by christianklotz** [comment]
👍 or alternatively put a note somewhere listing all non-enumerable properties. Do you know of a good "pure JavaScript" explanation/API/documentation that has something similar?
