### ISSUE TITLE
Add action for path edit

### ISSUE THREAD

**Issue by TimBest** [sketch-hq/SketchAPI#336]
I am working on a plugin that helps with making tessellating patterns.
some thing like this: 
![tesselation](https://user-images.githubusercontent.com/5008461/51009276-67f9fe00-1504-11e9-9879-c1dce6a7fa48.gif)

However instead of using 2 symbols it would use a single shape. Ideally I would like this plugin to work the same way as the transform tool.

Right now I am using the `SelectionChanged` event however that means to get the shape to update I need to toggle in and out of the path editing mode.

**Action to add:**  Focus/blur events on path points

**Comment by christianklotz** [comment]
The [`onDocumentChange`](https://developer.sketch.com/plugins/document-changes) handler covers point edits. While it does not trigger changes while moving the point for performance reasons it does update once the mouse is released.

Closing for now since it covers the original request for adding actions for _blur_. If you feel this does not cover it, let me know.
