### ISSUE TITLE
Add action for color picker

### ISSUE THREAD

**Issue by huw** [sketch-hq/SketchAPI#348]
Sketch 53 is adding some really nice features around the color picker, but there isn't a programmatic way to check when the user has picked a color. Our org is building a plugin to track adoption of our design system, and we'd really love to be able to track which colors our designers are using as a component of that.

We would love something like being able to look at `context.color.colorName` and `context.color.hex` or something similar to that — is this possible?

**Comment by christianklotz** [comment]
Closing since we introduced the new `onDocumentChange` handler as a universal way to be notified of document changes, see https://developer.sketch.com/plugins/document-changes.

Let me know if this works for your use case surrounding colour changes or, if it doesn't, how you could see it working within the document change handler.
