### ISSUE TITLE
Consider using GitHub releases to communicate API changes

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#420]
Perhaps in addition to using the `CHANGELOG.json` y'all could use the releases feature to better communicate API changes? I think a good example of a project that uses the releases tab well is react-beautiful-dnd https://github.com/atlassian/react-beautiful-dnd/releases

**Comment by jedrichards** [comment]
A problem with this is that the releases tab of GitHub is designed to work alongside a versioning system and git tags, so it has functionality/meaning over and above just being a pretty changelog. SketchAPI isn't released in any ordinary sense, since its baked into Sketch in an opaque process that isn't publicly visible, automated or tied to a semantic "version" within this repo. We could co-opt the releases tab and add releases/tags that mirrored Sketch's releases but I'd be concerned that was sending some confusing messages about what's going on.

**Comment by christianklotz** [comment]
Closing for now. SketchAPI is built as part the Sketch app and we don't switch between releases.
