### ISSUE TITLE
https://developer.sketch.com/api

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#505]
With the new documentation there are these urls

- https://developer.sketch.com/plugins/
- https://developer.sketch.com/cli/
- https://developer.sketch.com/file-format/
- https://developer.sketch.com/app

that go all along the top nav but the API is still at

- https://developer.sketch.com/reference/api/

Could the old url redirect to https://developer.sketch.com/api/ ?

**Comment by christianklotz** [comment]
The API technically falls under plugins, which contains besides pages on the various concepts in https://developer.sketch.com/plugins/ also the https://developer.sketch.com/plugins/reference which redirects to https://developer.sketch.com/reference/api/.

The top navigation entry for the API is really more of a convenience, not an element on the same level as the rest, added because we know this is often what people are looking for. Closing for now.
