### ISSUE TITLE
Unable to remove imported symbol

### ISSUE THREAD

**Issue by peerjollux** [sketch-hq/SketchAPI#673]
I'm trying to remove an imported symbolMaster but somehow it does not work. On a regular symbolMaster is does work.

```
const document = require('sketch').getSelectedDocument()
const symbols = document.getSymbols()
symbols[0].remove()
```

**Comment by christianklotz** [comment]
By imported I guess you mean a Symbol from a Library. Note that `getSymbols` returns the list of Symbol Masters, not Instances and a Symbol Master linked from a library cannot be removed from said library, contrary to Symbols defined in the current document as you rightly pointed out.

Closing since it works as expected.
