### ISSUE TITLE
Actions of remove a page using SketchAPI can not undo 

### ISSUE THREAD

**Issue by funfungo** [sketch-hq/SketchAPI#769]
I am using SketchAPI to process some sketch file. all I want to do is remove some pages that unnecessary, save the file into a new document , and restore the original file.

But when I remove pages through SketchAPI, it can't be restored by any way.

For example,  if I remove the selected page by
`document.selectedPage.remove();`

And using code restore the page by 
```
function actionWithType(context, type) {
  var controller = context.document.actionsController();

  if (controller.actionWithName) {
    return controller.actionWithName(type);
  } else if (controller.actionWithID) {
    return controller.actionWithID(type);
  } else {
    return controller.actionForID(type);
  }
}

actionWithType(context, "MSUndoAction").doPerformAction(nil);
```

there is nothing happend, and the undo action in the edit menu is gray(which means there's nothing to undo)

**Comment by KevinGutowski** [comment]
When you run a script all actions done in that script are bundled together and one History Moment is created for that action. See ([MSHistory](https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSHistory.h) and [MSMoment](https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSMoment.h)). I highly recommend against messing with those internal objects but I thought I would clarify what is likely going on with the execution of your code.

Not really sure what possible solutions there are for your specific situation but I would first try using a [fiber](https://developer.sketch.com/reference/api/#async) and seeing if you can break apart the javascript calls so that they each get corresponding history moments created.
