### ISSUE TITLE
Eye-Tracking Plugin

### ISSUE THREAD

**Issue by realCommitment** [sketch-hq/SketchAPI#796]
Hey guys, 
I am trying to develop an eye-tracking plugin for Sketch as part of my masters thesis. The use case is to allow users to control the UI using mouse and eye tracker at the same time and having specific actions evoked (color pallete for instance) if user gazes at something for longer period of time. 

So my question is whether it is possible to connect eye-tracking input device to current API and whether this plugin would be able to run in the background?

**Comment by realCommitment** [comment]
Thank you for your responses in advance

**Comment by christianklotz** [comment]
It's usually best to use https://sketchplugins.com for questions around the plugin API, especially since there will be others from the design community with potential ideas on how to address this idea. My quick take would be that this may only be feasible involving a native framework and then rely on the macOS APIs.
